services:
  - type: web
    name: st-joseph-church-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REACT_APP_API_URL
        value: https://st-joseph-church-api.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false 